/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Providers } from "./Providers";
import { ProvidersCountArgs } from "./ProvidersCountArgs";
import { ProvidersFindManyArgs } from "./ProvidersFindManyArgs";
import { ProvidersFindUniqueArgs } from "./ProvidersFindUniqueArgs";
import { DeleteProvidersArgs } from "./DeleteProvidersArgs";
import { ProvidersService } from "../providers.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Providers)
export class ProvidersResolverBase {
  constructor(
    protected readonly service: ProvidersService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Providers",
    action: "read",
    possession: "any",
  })
  async _providersItemsMeta(
    @graphql.Args() args: ProvidersCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Providers])
  @nestAccessControl.UseRoles({
    resource: "Providers",
    action: "read",
    possession: "any",
  })
  async providersItems(
    @graphql.Args() args: ProvidersFindManyArgs
  ): Promise<Providers[]> {
    return this.service.providersItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Providers, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Providers",
    action: "read",
    possession: "own",
  })
  async providers(
    @graphql.Args() args: ProvidersFindUniqueArgs
  ): Promise<Providers | null> {
    const result = await this.service.providers(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Providers)
  @nestAccessControl.UseRoles({
    resource: "Providers",
    action: "delete",
    possession: "any",
  })
  async deleteProviders(
    @graphql.Args() args: DeleteProvidersArgs
  ): Promise<Providers | null> {
    try {
      return await this.service.deleteProviders(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
