/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Conversations } from "./Conversations";
import { ConversationsCountArgs } from "./ConversationsCountArgs";
import { ConversationsFindManyArgs } from "./ConversationsFindManyArgs";
import { ConversationsFindUniqueArgs } from "./ConversationsFindUniqueArgs";
import { DeleteConversationsArgs } from "./DeleteConversationsArgs";
import { ConversationsService } from "../conversations.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Conversations)
export class ConversationsResolverBase {
  constructor(
    protected readonly service: ConversationsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Conversations",
    action: "read",
    possession: "any",
  })
  async _conversationsItemsMeta(
    @graphql.Args() args: ConversationsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Conversations])
  @nestAccessControl.UseRoles({
    resource: "Conversations",
    action: "read",
    possession: "any",
  })
  async conversationsItems(
    @graphql.Args() args: ConversationsFindManyArgs
  ): Promise<Conversations[]> {
    return this.service.conversationsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Conversations, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Conversations",
    action: "read",
    possession: "own",
  })
  async conversations(
    @graphql.Args() args: ConversationsFindUniqueArgs
  ): Promise<Conversations | null> {
    const result = await this.service.conversations(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Conversations)
  @nestAccessControl.UseRoles({
    resource: "Conversations",
    action: "delete",
    possession: "any",
  })
  async deleteConversations(
    @graphql.Args() args: DeleteConversationsArgs
  ): Promise<Conversations | null> {
    try {
      return await this.service.deleteConversations(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
