/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AccessLogsService } from "../accessLogs.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AccessLogsCreateInput } from "./AccessLogsCreateInput";
import { AccessLogs } from "./AccessLogs";
import { AccessLogsFindManyArgs } from "./AccessLogsFindManyArgs";
import { AccessLogsWhereUniqueInput } from "./AccessLogsWhereUniqueInput";
import { AccessLogsUpdateInput } from "./AccessLogsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AccessLogsControllerBase {
  constructor(
    protected readonly service: AccessLogsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AccessLogs })
  @nestAccessControl.UseRoles({
    resource: "AccessLogs",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAccessLogs(
    @common.Body() data: AccessLogsCreateInput
  ): Promise<AccessLogs> {
    return await this.service.createAccessLogs({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        dateTime: true,
        device: true,
        id: true,
        ip: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AccessLogs] })
  @ApiNestedQuery(AccessLogsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AccessLogs",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async accessLogsItems(@common.Req() request: Request): Promise<AccessLogs[]> {
    const args = plainToClass(AccessLogsFindManyArgs, request.query);
    return this.service.accessLogsItems({
      ...args,
      select: {
        createdAt: true,
        dateTime: true,
        device: true,
        id: true,
        ip: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AccessLogs })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AccessLogs",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async accessLogs(
    @common.Param() params: AccessLogsWhereUniqueInput
  ): Promise<AccessLogs | null> {
    const result = await this.service.accessLogs({
      where: params,
      select: {
        createdAt: true,
        dateTime: true,
        device: true,
        id: true,
        ip: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AccessLogs })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AccessLogs",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAccessLogs(
    @common.Param() params: AccessLogsWhereUniqueInput,
    @common.Body() data: AccessLogsUpdateInput
  ): Promise<AccessLogs | null> {
    try {
      return await this.service.updateAccessLogs({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          dateTime: true,
          device: true,
          id: true,
          ip: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AccessLogs })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AccessLogs",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAccessLogs(
    @common.Param() params: AccessLogsWhereUniqueInput
  ): Promise<AccessLogs | null> {
    try {
      return await this.service.deleteAccessLogs({
        where: params,
        select: {
          createdAt: true,
          dateTime: true,
          device: true,
          id: true,
          ip: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
