/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AssistantSettingsService } from "../assistantSettings.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AssistantSettingsCreateInput } from "./AssistantSettingsCreateInput";
import { AssistantSettings } from "./AssistantSettings";
import { AssistantSettingsFindManyArgs } from "./AssistantSettingsFindManyArgs";
import { AssistantSettingsWhereUniqueInput } from "./AssistantSettingsWhereUniqueInput";
import { AssistantSettingsUpdateInput } from "./AssistantSettingsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AssistantSettingsControllerBase {
  constructor(
    protected readonly service: AssistantSettingsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AssistantSettings })
  @nestAccessControl.UseRoles({
    resource: "AssistantSettings",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAssistantSettings(
    @common.Body() data: AssistantSettingsCreateInput
  ): Promise<AssistantSettings> {
    return await this.service.createAssistantSettings({
      data: {
        ...data,

        assistant: data.assistant
          ? {
              connect: data.assistant,
            }
          : undefined,
      },
      select: {
        assistant: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        settingName: true,
        settingValue: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AssistantSettings] })
  @ApiNestedQuery(AssistantSettingsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AssistantSettings",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async assistantSettingsItems(
    @common.Req() request: Request
  ): Promise<AssistantSettings[]> {
    const args = plainToClass(AssistantSettingsFindManyArgs, request.query);
    return this.service.assistantSettingsItems({
      ...args,
      select: {
        assistant: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        settingName: true,
        settingValue: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AssistantSettings })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssistantSettings",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async assistantSettings(
    @common.Param() params: AssistantSettingsWhereUniqueInput
  ): Promise<AssistantSettings | null> {
    const result = await this.service.assistantSettings({
      where: params,
      select: {
        assistant: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        settingName: true,
        settingValue: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AssistantSettings })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssistantSettings",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAssistantSettings(
    @common.Param() params: AssistantSettingsWhereUniqueInput,
    @common.Body() data: AssistantSettingsUpdateInput
  ): Promise<AssistantSettings | null> {
    try {
      return await this.service.updateAssistantSettings({
        where: params,
        data: {
          ...data,

          assistant: data.assistant
            ? {
                connect: data.assistant,
              }
            : undefined,
        },
        select: {
          assistant: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          settingName: true,
          settingValue: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AssistantSettings })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssistantSettings",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAssistantSettings(
    @common.Param() params: AssistantSettingsWhereUniqueInput
  ): Promise<AssistantSettings | null> {
    try {
      return await this.service.deleteAssistantSettings({
        where: params,
        select: {
          assistant: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          settingName: true,
          settingValue: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
