/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserTypes } from "./UserTypes";
import { UserTypesCountArgs } from "./UserTypesCountArgs";
import { UserTypesFindManyArgs } from "./UserTypesFindManyArgs";
import { UserTypesFindUniqueArgs } from "./UserTypesFindUniqueArgs";
import { DeleteUserTypesArgs } from "./DeleteUserTypesArgs";
import { UserTypesService } from "../userTypes.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserTypes)
export class UserTypesResolverBase {
  constructor(
    protected readonly service: UserTypesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserTypes",
    action: "read",
    possession: "any",
  })
  async _userTypesItemsMeta(
    @graphql.Args() args: UserTypesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserTypes])
  @nestAccessControl.UseRoles({
    resource: "UserTypes",
    action: "read",
    possession: "any",
  })
  async userTypesItems(
    @graphql.Args() args: UserTypesFindManyArgs
  ): Promise<UserTypes[]> {
    return this.service.userTypesItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserTypes, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserTypes",
    action: "read",
    possession: "own",
  })
  async userTypes(
    @graphql.Args() args: UserTypesFindUniqueArgs
  ): Promise<UserTypes | null> {
    const result = await this.service.userTypes(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserTypes)
  @nestAccessControl.UseRoles({
    resource: "UserTypes",
    action: "delete",
    possession: "any",
  })
  async deleteUserTypes(
    @graphql.Args() args: DeleteUserTypesArgs
  ): Promise<UserTypes | null> {
    try {
      return await this.service.deleteUserTypes(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
