/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MessageTypes } from "./MessageTypes";
import { MessageTypesCountArgs } from "./MessageTypesCountArgs";
import { MessageTypesFindManyArgs } from "./MessageTypesFindManyArgs";
import { MessageTypesFindUniqueArgs } from "./MessageTypesFindUniqueArgs";
import { DeleteMessageTypesArgs } from "./DeleteMessageTypesArgs";
import { MessageTypesService } from "../messageTypes.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MessageTypes)
export class MessageTypesResolverBase {
  constructor(
    protected readonly service: MessageTypesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MessageTypes",
    action: "read",
    possession: "any",
  })
  async _messageTypesItemsMeta(
    @graphql.Args() args: MessageTypesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MessageTypes])
  @nestAccessControl.UseRoles({
    resource: "MessageTypes",
    action: "read",
    possession: "any",
  })
  async messageTypesItems(
    @graphql.Args() args: MessageTypesFindManyArgs
  ): Promise<MessageTypes[]> {
    return this.service.messageTypesItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MessageTypes, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MessageTypes",
    action: "read",
    possession: "own",
  })
  async messageTypes(
    @graphql.Args() args: MessageTypesFindUniqueArgs
  ): Promise<MessageTypes | null> {
    const result = await this.service.messageTypes(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MessageTypes)
  @nestAccessControl.UseRoles({
    resource: "MessageTypes",
    action: "delete",
    possession: "any",
  })
  async deleteMessageTypes(
    @graphql.Args() args: DeleteMessageTypesArgs
  ): Promise<MessageTypes | null> {
    try {
      return await this.service.deleteMessageTypes(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
