/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AssistantTypesService } from "../assistantTypes.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AssistantTypesCreateInput } from "./AssistantTypesCreateInput";
import { AssistantTypes } from "./AssistantTypes";
import { AssistantTypesFindManyArgs } from "./AssistantTypesFindManyArgs";
import { AssistantTypesWhereUniqueInput } from "./AssistantTypesWhereUniqueInput";
import { AssistantTypesUpdateInput } from "./AssistantTypesUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AssistantTypesControllerBase {
  constructor(
    protected readonly service: AssistantTypesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AssistantTypes })
  @nestAccessControl.UseRoles({
    resource: "AssistantTypes",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAssistantTypes(
    @common.Body() data: AssistantTypesCreateInput
  ): Promise<AssistantTypes> {
    return await this.service.createAssistantTypes({
      data: data,
      select: {
        createdAt: true,
        id: true,
        typeName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AssistantTypes] })
  @ApiNestedQuery(AssistantTypesFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AssistantTypes",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async assistantTypesItems(
    @common.Req() request: Request
  ): Promise<AssistantTypes[]> {
    const args = plainToClass(AssistantTypesFindManyArgs, request.query);
    return this.service.assistantTypesItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        typeName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AssistantTypes })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssistantTypes",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async assistantTypes(
    @common.Param() params: AssistantTypesWhereUniqueInput
  ): Promise<AssistantTypes | null> {
    const result = await this.service.assistantTypes({
      where: params,
      select: {
        createdAt: true,
        id: true,
        typeName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AssistantTypes })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssistantTypes",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAssistantTypes(
    @common.Param() params: AssistantTypesWhereUniqueInput,
    @common.Body() data: AssistantTypesUpdateInput
  ): Promise<AssistantTypes | null> {
    try {
      return await this.service.updateAssistantTypes({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          typeName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AssistantTypes })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssistantTypes",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAssistantTypes(
    @common.Param() params: AssistantTypesWhereUniqueInput
  ): Promise<AssistantTypes | null> {
    try {
      return await this.service.deleteAssistantTypes({
        where: params,
        select: {
          createdAt: true,
          id: true,
          typeName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
