/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ActivityLog } from "./ActivityLog";
import { ActivityLogCountArgs } from "./ActivityLogCountArgs";
import { ActivityLogFindManyArgs } from "./ActivityLogFindManyArgs";
import { ActivityLogFindUniqueArgs } from "./ActivityLogFindUniqueArgs";
import { CreateActivityLogArgs } from "./CreateActivityLogArgs";
import { UpdateActivityLogArgs } from "./UpdateActivityLogArgs";
import { DeleteActivityLogArgs } from "./DeleteActivityLogArgs";
import { User } from "../../user/base/User";
import { ActivityLogService } from "../activityLog.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ActivityLog)
export class ActivityLogResolverBase {
  constructor(
    protected readonly service: ActivityLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ActivityLog",
    action: "read",
    possession: "any",
  })
  async _activityLogsMeta(
    @graphql.Args() args: ActivityLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ActivityLog])
  @nestAccessControl.UseRoles({
    resource: "ActivityLog",
    action: "read",
    possession: "any",
  })
  async activityLogs(
    @graphql.Args() args: ActivityLogFindManyArgs
  ): Promise<ActivityLog[]> {
    return this.service.activityLogs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ActivityLog, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ActivityLog",
    action: "read",
    possession: "own",
  })
  async activityLog(
    @graphql.Args() args: ActivityLogFindUniqueArgs
  ): Promise<ActivityLog | null> {
    const result = await this.service.activityLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ActivityLog)
  @nestAccessControl.UseRoles({
    resource: "ActivityLog",
    action: "create",
    possession: "any",
  })
  async createActivityLog(
    @graphql.Args() args: CreateActivityLogArgs
  ): Promise<ActivityLog> {
    return await this.service.createActivityLog({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ActivityLog)
  @nestAccessControl.UseRoles({
    resource: "ActivityLog",
    action: "update",
    possession: "any",
  })
  async updateActivityLog(
    @graphql.Args() args: UpdateActivityLogArgs
  ): Promise<ActivityLog | null> {
    try {
      return await this.service.updateActivityLog({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ActivityLog)
  @nestAccessControl.UseRoles({
    resource: "ActivityLog",
    action: "delete",
    possession: "any",
  })
  async deleteActivityLog(
    @graphql.Args() args: DeleteActivityLogArgs
  ): Promise<ActivityLog | null> {
    try {
      return await this.service.deleteActivityLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: ActivityLog): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
