/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OpenAiAssistant } from "./OpenAiAssistant";
import { OpenAiAssistantCountArgs } from "./OpenAiAssistantCountArgs";
import { OpenAiAssistantFindManyArgs } from "./OpenAiAssistantFindManyArgs";
import { OpenAiAssistantFindUniqueArgs } from "./OpenAiAssistantFindUniqueArgs";
import { DeleteOpenAiAssistantArgs } from "./DeleteOpenAiAssistantArgs";
import { OpenAiAssistantService } from "../openAiAssistant.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => OpenAiAssistant)
export class OpenAiAssistantResolverBase {
  constructor(
    protected readonly service: OpenAiAssistantService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "OpenAiAssistant",
    action: "read",
    possession: "any",
  })
  async _openAiAssistantsMeta(
    @graphql.Args() args: OpenAiAssistantCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [OpenAiAssistant])
  @nestAccessControl.UseRoles({
    resource: "OpenAiAssistant",
    action: "read",
    possession: "any",
  })
  async openAiAssistants(
    @graphql.Args() args: OpenAiAssistantFindManyArgs
  ): Promise<OpenAiAssistant[]> {
    return this.service.openAiAssistants(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => OpenAiAssistant, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "OpenAiAssistant",
    action: "read",
    possession: "own",
  })
  async openAiAssistant(
    @graphql.Args() args: OpenAiAssistantFindUniqueArgs
  ): Promise<OpenAiAssistant | null> {
    const result = await this.service.openAiAssistant(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OpenAiAssistant)
  @nestAccessControl.UseRoles({
    resource: "OpenAiAssistant",
    action: "delete",
    possession: "any",
  })
  async deleteOpenAiAssistant(
    @graphql.Args() args: DeleteOpenAiAssistantArgs
  ): Promise<OpenAiAssistant | null> {
    try {
      return await this.service.deleteOpenAiAssistant(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
