/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SessionStatuses } from "./SessionStatuses";
import { SessionStatusesCountArgs } from "./SessionStatusesCountArgs";
import { SessionStatusesFindManyArgs } from "./SessionStatusesFindManyArgs";
import { SessionStatusesFindUniqueArgs } from "./SessionStatusesFindUniqueArgs";
import { DeleteSessionStatusesArgs } from "./DeleteSessionStatusesArgs";
import { SessionStatusesService } from "../sessionStatuses.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SessionStatuses)
export class SessionStatusesResolverBase {
  constructor(
    protected readonly service: SessionStatusesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SessionStatuses",
    action: "read",
    possession: "any",
  })
  async _sessionStatusesItemsMeta(
    @graphql.Args() args: SessionStatusesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SessionStatuses])
  @nestAccessControl.UseRoles({
    resource: "SessionStatuses",
    action: "read",
    possession: "any",
  })
  async sessionStatusesItems(
    @graphql.Args() args: SessionStatusesFindManyArgs
  ): Promise<SessionStatuses[]> {
    return this.service.sessionStatusesItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SessionStatuses, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SessionStatuses",
    action: "read",
    possession: "own",
  })
  async sessionStatuses(
    @graphql.Args() args: SessionStatusesFindUniqueArgs
  ): Promise<SessionStatuses | null> {
    const result = await this.service.sessionStatuses(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SessionStatuses)
  @nestAccessControl.UseRoles({
    resource: "SessionStatuses",
    action: "delete",
    possession: "any",
  })
  async deleteSessionStatuses(
    @graphql.Args() args: DeleteSessionStatusesArgs
  ): Promise<SessionStatuses | null> {
    try {
      return await this.service.deleteSessionStatuses(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
